import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1776979576997 implements MigrationInterface {
    name = 'Migration1776979576997'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('ADMIN', 'DEVELOPMENT_WING', 'WORKS_AND_SERVICES', 'PND_WING', 'FINANCE_DEPARTMENT', 'COMPETENT_AUTHORITY')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullName" character varying(150) NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."adp_scheme_documents_document_type_enum" AS ENUM('PC1', 'PC2', 'ECNEC', 'APPROVAL_LETTER', 'REVISION', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "adp_scheme_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adp_scheme_id" uuid NOT NULL, "document_type" "public"."adp_scheme_documents_document_type_enum" NOT NULL DEFAULT 'OTHER', "document_name" character varying(255) NOT NULL, "caption" character varying(255), "document_path" character varying(1000) NOT NULL, "mime_type" character varying(100), "file_size" bigint, "remarks" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_00c974aab7d8e4939d623c698f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "adp_scheme_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adp_scheme_id" uuid NOT NULL, "comment" text NOT NULL, "commented_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d44bbbc83b910d04ac142b04f8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "adp_scheme_costings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adp_scheme_id" uuid NOT NULL, "financial_year" character varying(9) NOT NULL, "estimated_cost_cap" numeric(15,2) NOT NULL DEFAULT '0', "estimated_cost_rev" numeric(15,2) NOT NULL DEFAULT '0', "estimated_cost_total" numeric(15,2) NOT NULL DEFAULT '0', "prior_exp_cap" numeric(15,2) NOT NULL DEFAULT '0', "prior_exp_rev" numeric(15,2) NOT NULL DEFAULT '0', "prior_exp_total" numeric(15,2) NOT NULL DEFAULT '0', "throw_forward_cap" numeric(15,2) NOT NULL DEFAULT '0', "throw_forward_rev" numeric(15,2) NOT NULL DEFAULT '0', "throw_forward_total" numeric(15,2) NOT NULL DEFAULT '0', "alloc_cfy_cap" numeric(15,2) NOT NULL DEFAULT '0', "alloc_cfy_rev" numeric(15,2) NOT NULL DEFAULT '0', "alloc_cfy_total" numeric(15,2) NOT NULL DEFAULT '0', "rev_alloc_cfy_cap" numeric(15,2) NOT NULL DEFAULT '0', "rev_alloc_cfy_rev" numeric(15,2) NOT NULL DEFAULT '0', "rev_alloc_cfy_total" numeric(15,2) NOT NULL DEFAULT '0', "releases_cfy_cap" numeric(15,2) NOT NULL DEFAULT '0', "releases_cfy_rev" numeric(15,2) NOT NULL DEFAULT '0', "releases_cfy_total" numeric(15,2) NOT NULL DEFAULT '0', "module_a_cap" numeric(15,2) NOT NULL DEFAULT '0', "module_a_rev" numeric(15,2) NOT NULL DEFAULT '0', "module_a_total" numeric(15,2) NOT NULL DEFAULT '0', "module_b_cap" numeric(15,2) NOT NULL DEFAULT '0', "module_b_rev" numeric(15,2) NOT NULL DEFAULT '0', "module_b_total" numeric(15,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_adp_scheme_costing_financial_year_scheme" UNIQUE ("financial_year", "adp_scheme_id"), CONSTRAINT "CHK_f1e22f36c2d40714a489f7f2c4" CHECK ("module_b_total" = "module_b_cap" + "module_b_rev"), CONSTRAINT "CHK_008739d15661429def0a87d802" CHECK ("module_a_total" = "module_a_cap" + "module_a_rev"), CONSTRAINT "CHK_9e99c478e823444c1d3c2353aa" CHECK ("releases_cfy_total" = "releases_cfy_cap" + "releases_cfy_rev"), CONSTRAINT "CHK_e70a26a4aed0332bf4a0e1aaf0" CHECK ("rev_alloc_cfy_total" = "rev_alloc_cfy_cap" + "rev_alloc_cfy_rev"), CONSTRAINT "CHK_a4b56e5c369d465b8d5ace9088" CHECK ("alloc_cfy_total" = "alloc_cfy_cap" + "alloc_cfy_rev"), CONSTRAINT "CHK_4055100fa6eec5766b4d522bc1" CHECK ("throw_forward_total" = "throw_forward_cap" + "throw_forward_rev"), CONSTRAINT "CHK_8f06cab92b4fdb504a8444aa64" CHECK ("prior_exp_total" = "prior_exp_cap" + "prior_exp_rev"), CONSTRAINT "CHK_a337fcdea30e78e91111d72444" CHECK ("estimated_cost_total" = "estimated_cost_cap" + "estimated_cost_rev"), CONSTRAINT "PK_4b9f1785e4a1b6ef2974e2f9299" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."adp_scheme_workflow_logs_fromstage_enum" AS ENUM('PROPOSAL_AND_FEASIBILITY', 'ADP_DRAFTING', 'PC1_COSTING', 'SCRUTINY', 'PND_AND_APPROVALS', 'FINANCE_RELEASE', 'COMPLETED')`);
        await queryRunner.query(`CREATE TYPE "public"."adp_scheme_workflow_logs_tostage_enum" AS ENUM('PROPOSAL_AND_FEASIBILITY', 'ADP_DRAFTING', 'PC1_COSTING', 'SCRUTINY', 'PND_AND_APPROVALS', 'FINANCE_RELEASE', 'COMPLETED')`);
        await queryRunner.query(`CREATE TYPE "public"."adp_scheme_workflow_logs_fromstep_enum" AS ENUM('SUBMIT_PROPOSAL', 'REVIEW_AND_ROUTE', 'SUBMIT_FOR_ENDORSEMENT', 'ENDORSE', 'CREATE_ADP_DRAFT', 'PND_FEEDBACK', 'REVISE_DRAFT', 'INITIATE_PC1', 'MODULE_A_COSTS', 'MODULE_B_COSTS', 'INTERNAL_SCRUTINY', 'DDWP_PRE_PDWP_PDWP_APPROVAL', 'ISSUE_NOC', 'AUTH_LETTER_TO_FINANCE', 'RELEASE_FUNDS', 'UPDATE_FUND_RELEASE_STATUS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TYPE "public"."adp_scheme_workflow_logs_tostep_enum" AS ENUM('SUBMIT_PROPOSAL', 'REVIEW_AND_ROUTE', 'SUBMIT_FOR_ENDORSEMENT', 'ENDORSE', 'CREATE_ADP_DRAFT', 'PND_FEEDBACK', 'REVISE_DRAFT', 'INITIATE_PC1', 'MODULE_A_COSTS', 'MODULE_B_COSTS', 'INTERNAL_SCRUTINY', 'DDWP_PRE_PDWP_PDWP_APPROVAL', 'ISSUE_NOC', 'AUTH_LETTER_TO_FINANCE', 'RELEASE_FUNDS', 'UPDATE_FUND_RELEASE_STATUS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "adp_scheme_workflow_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scheme_id" uuid NOT NULL, "acted_by_user_id" uuid, "fromStage" "public"."adp_scheme_workflow_logs_fromstage_enum" NOT NULL, "toStage" "public"."adp_scheme_workflow_logs_tostage_enum" NOT NULL, "fromStep" "public"."adp_scheme_workflow_logs_fromstep_enum" NOT NULL, "toStep" "public"."adp_scheme_workflow_logs_tostep_enum" NOT NULL, "remarks" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1fc6d90df2dda318b2480fad8c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."adp_schemes_type_enum" AS ENUM('ONGOING', 'NEW')`);
        await queryRunner.query(`CREATE TYPE "public"."adp_schemes_approval_status_enum" AS ENUM('DRAFT', 'APPROVED', 'PENDING', 'REJECTED', 'UNDER_REVISION', 'UNAPPROVED', 'APPROVAL_PENDING')`);
        await queryRunner.query(`CREATE TYPE "public"."adp_schemes_execution_status_enum" AS ENUM('NOT_STARTED', 'CONTINUE', 'COMPLETED', 'ON_HOLD', 'DROPPED', 'UNSATISFACTORY')`);
        await queryRunner.query(`CREATE TYPE "public"."adp_schemes_current_stage_enum" AS ENUM('PROPOSAL_AND_FEASIBILITY', 'ADP_DRAFTING', 'PC1_COSTING', 'SCRUTINY', 'PND_AND_APPROVALS', 'FINANCE_RELEASE', 'COMPLETED')`);
        await queryRunner.query(`CREATE TYPE "public"."adp_schemes_current_step_enum" AS ENUM('SUBMIT_PROPOSAL', 'REVIEW_AND_ROUTE', 'SUBMIT_FOR_ENDORSEMENT', 'ENDORSE', 'CREATE_ADP_DRAFT', 'PND_FEEDBACK', 'REVISE_DRAFT', 'INITIATE_PC1', 'MODULE_A_COSTS', 'MODULE_B_COSTS', 'INTERNAL_SCRUTINY', 'DDWP_PRE_PDWP_PDWP_APPROVAL', 'ISSUE_NOC', 'AUTH_LETTER_TO_FINANCE', 'RELEASE_FUNDS', 'UPDATE_FUND_RELEASE_STATUS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "adp_schemes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adp_no" character varying(100) NOT NULL, "scheme_name" character varying(500) NOT NULL, "district" character varying(150), "sector" character varying(200), "type" "public"."adp_schemes_type_enum", "sub_type" character varying(200), "approval_status" "public"."adp_schemes_approval_status_enum" NOT NULL DEFAULT 'DRAFT', "execution_status" "public"."adp_schemes_execution_status_enum" NOT NULL DEFAULT 'NOT_STARTED', "initial_approval_date" date, "target_date" date, "is_active" boolean NOT NULL DEFAULT true, "current_stage" "public"."adp_schemes_current_stage_enum" NOT NULL DEFAULT 'PROPOSAL_AND_FEASIBILITY', "current_step" "public"."adp_schemes_current_step_enum" NOT NULL DEFAULT 'SUBMIT_PROPOSAL', "current_step_updated_at" TIMESTAMP, "workflow_completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c52beed0ee94c79ce91aa6d3cec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c144d11ff3d17ef18968f22d7" ON "adp_schemes" ("adp_no") `);
        await queryRunner.query(`ALTER TABLE "adp_scheme_documents" ADD CONSTRAINT "FK_1c14f09c7ee52371de273638a27" FOREIGN KEY ("adp_scheme_id") REFERENCES "adp_schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adp_scheme_comments" ADD CONSTRAINT "FK_6f1265a2bdc499d4ce6cd7a404d" FOREIGN KEY ("adp_scheme_id") REFERENCES "adp_schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adp_scheme_costings" ADD CONSTRAINT "FK_cfe36e8b1d7025337d0b3f40adc" FOREIGN KEY ("adp_scheme_id") REFERENCES "adp_schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adp_scheme_workflow_logs" ADD CONSTRAINT "FK_6ee77b40704a09683698bd9f450" FOREIGN KEY ("scheme_id") REFERENCES "adp_schemes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adp_scheme_workflow_logs" ADD CONSTRAINT "FK_18056d90ba9797c05759da692b7" FOREIGN KEY ("acted_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "adp_scheme_workflow_logs" DROP CONSTRAINT "FK_18056d90ba9797c05759da692b7"`);
        await queryRunner.query(`ALTER TABLE "adp_scheme_workflow_logs" DROP CONSTRAINT "FK_6ee77b40704a09683698bd9f450"`);
        await queryRunner.query(`ALTER TABLE "adp_scheme_costings" DROP CONSTRAINT "FK_cfe36e8b1d7025337d0b3f40adc"`);
        await queryRunner.query(`ALTER TABLE "adp_scheme_comments" DROP CONSTRAINT "FK_6f1265a2bdc499d4ce6cd7a404d"`);
        await queryRunner.query(`ALTER TABLE "adp_scheme_documents" DROP CONSTRAINT "FK_1c14f09c7ee52371de273638a27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c144d11ff3d17ef18968f22d7"`);
        await queryRunner.query(`DROP TABLE "adp_schemes"`);
        await queryRunner.query(`DROP TYPE "public"."adp_schemes_current_step_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adp_schemes_current_stage_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adp_schemes_execution_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adp_schemes_approval_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adp_schemes_type_enum"`);
        await queryRunner.query(`DROP TABLE "adp_scheme_workflow_logs"`);
        await queryRunner.query(`DROP TYPE "public"."adp_scheme_workflow_logs_tostep_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adp_scheme_workflow_logs_fromstep_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adp_scheme_workflow_logs_tostage_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adp_scheme_workflow_logs_fromstage_enum"`);
        await queryRunner.query(`DROP TABLE "adp_scheme_costings"`);
        await queryRunner.query(`DROP TABLE "adp_scheme_comments"`);
        await queryRunner.query(`DROP TABLE "adp_scheme_documents"`);
        await queryRunner.query(`DROP TYPE "public"."adp_scheme_documents_document_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
    }

}
