export enum AdpApprovalStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  UNDER_REVISION = 'UNDER_REVISION',
  UNAPPROVED = 'UNAPPROVED',
  APPROVAL_PENDING = 'APPROVAL_PENDING',
}

export enum AdpExecutionStatus {
  NOT_STARTED = 'NOT_STARTED',
  CONTINUE = 'CONTINUE',
  COMPLETED = 'COMPLETED',
  ON_HOLD = 'ON_HOLD',
  DROPPED = 'DROPPED',
  UNSATISFACTORY = 'UNSATISFACTORY',
}

export enum AdpSchemeType {
  ONGOING = 'ONGOING',
  NEW = 'NEW',
}

export enum AdpSchemeDocumentType {
  PC1 = 'PC1',
  PC2 = 'PC2',
  ECNEC = 'ECNEC',
  APPROVAL_LETTER = 'APPROVAL_LETTER',
  REVISION = 'REVISION',
  OTHER = 'OTHER',
}
export enum UserRole {
  ADMIN = 'ADMIN',
  DEVELOPMENT_WING = 'DEVELOPMENT_WING',
  WORKS_AND_SERVICES = 'WORKS_AND_SERVICES',
  PND_WING = 'PND_WING',
  FINANCE_DEPARTMENT = 'FINANCE_DEPARTMENT',
  COMPETENT_AUTHORITY = 'COMPETENT_AUTHORITY',
}
export enum AdpSchemeStage {
  PROPOSAL_AND_FEASIBILITY = 'PROPOSAL_AND_FEASIBILITY',
  ADP_DRAFTING = 'ADP_DRAFTING',
  PC1_COSTING = 'PC1_COSTING',
  SCRUTINY = 'SCRUTINY',
  PND_AND_APPROVALS = 'PND_AND_APPROVALS',
  FINANCE_RELEASE = 'FINANCE_RELEASE',
  COMPLETED = 'COMPLETED',
}

export enum AdpWorkflowStage {
  PROPOSAL_AND_FEASIBILITY = 'PROPOSAL_AND_FEASIBILITY',
  ADP_DRAFTING = 'ADP_DRAFTING',
  PC1_COSTING = 'PC1_COSTING',
  SCRUTINY = 'SCRUTINY',
  PND_AND_APPROVALS = 'PND_AND_APPROVALS',
  FINANCE_RELEASE = 'FINANCE_RELEASE',
  COMPLETED = 'COMPLETED',
}

export enum AdpWorkflowStep {
  SUBMIT_PROPOSAL = 'SUBMIT_PROPOSAL',
  REVIEW_AND_ROUTE = 'REVIEW_AND_ROUTE',
  SUBMIT_FOR_ENDORSEMENT = 'SUBMIT_FOR_ENDORSEMENT',
  ENDORSE = 'ENDORSE',

  CREATE_ADP_DRAFT = 'CREATE_ADP_DRAFT',
  PND_FEEDBACK = 'PND_FEEDBACK',
  REVISE_DRAFT = 'REVISE_DRAFT',

  INITIATE_PC1 = 'INITIATE_PC1',
  MODULE_A_COSTS = 'MODULE_A_COSTS',
  MODULE_B_COSTS = 'MODULE_B_COSTS',

  INTERNAL_SCRUTINY = 'INTERNAL_SCRUTINY',
  DDWP_PRE_PDWP_PDWP_APPROVAL = 'DDWP_PRE_PDWP_PDWP_APPROVAL',

  ISSUE_NOC = 'ISSUE_NOC',
  AUTH_LETTER_TO_FINANCE = 'AUTH_LETTER_TO_FINANCE',

  RELEASE_FUNDS = 'RELEASE_FUNDS',
  UPDATE_FUND_RELEASE_STATUS = 'UPDATE_FUND_RELEASE_STATUS',

  COMPLETED = 'COMPLETED',
}

export enum AdpSchemeStep {
  // Proposal and feasibility
  SUBMIT_PROPOSAL = 'SUBMIT_PROPOSAL',
  REVIEW_AND_ROUTE = 'REVIEW_AND_ROUTE',
  SUBMIT_FOR_ENDORSEMENT = 'SUBMIT_FOR_ENDORSEMENT',
  ENDORSE = 'ENDORSE',

  // ADP drafting
  CREATE_ADP_DRAFT = 'CREATE_ADP_DRAFT',
  PND_FEEDBACK = 'PND_FEEDBACK',
  REVISE_DRAFT = 'REVISE_DRAFT',

  // PC-1 costing
  INITIATE_PC1 = 'INITIATE_PC1',
  MODULE_A_COSTS = 'MODULE_A_COSTS',
  MODULE_B_COSTS = 'MODULE_B_COSTS',

  // Scrutiny
  INTERNAL_SCRUTINY = 'INTERNAL_SCRUTINY',
  DDWP_PRE_PDWP_PDWP_APPROVAL = 'DDWP_PRE_PDWP_PDWP_APPROVAL',

  // P&D / approval / finance
  ISSUE_NOC = 'ISSUE_NOC',
  AUTH_LETTER_TO_FINANCE = 'AUTH_LETTER_TO_FINANCE',
  RELEASE_FUNDS = 'RELEASE_FUNDS',
  UPDATE_FUND_RELEASE_STATUS = 'UPDATE_FUND_RELEASE_STATUS',

  COMPLETED = 'COMPLETED',
}